services:
  travsus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
        CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
        CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
        CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
        CLOUDINARY_URL: ${CLOUDINARY_URL}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_URL_PLACES: ${DATABASE_URL_PLACES}
        EMAIL_FROM: ${EMAIL_FROM}
        EMAIL_SERVER: ${EMAIL_SERVER}
        FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
        FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_COMPANY_PROFILE: ${NEXT_PUBLIC_COMPANY_PROFILE}
        NEXT_PUBLIC_COMPANY_REGISTRATION_NUMBER: ${NEXT_PUBLIC_COMPANY_REGISTRATION_NUMBER}
        NEXT_PUBLIC_EXTERNAL_SERVER: ${NEXT_PUBLIC_EXTERNAL_SERVER}
        NEXT_PUBLIC_LEGAL_LOCATION: ${NEXT_PUBLIC_LEGAL_LOCATION}
        NEXT_PUBLIC_LEGAL_NAME: ${NEXT_PUBLIC_LEGAL_NAME}
        NEXT_PUBLIC_PLATFROM_NAME: ${NEXT_PUBLIC_PLATFROM_NAME}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        POSTMARK_API_TOKEN: ${POSTMARK_API_TOKEN}
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        TRIPADVISOR_ACCESS_TOKEN: ${TRIPADVISOR_ACCESS_TOKEN}
        TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
        TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}

    container_name: travsus
    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.local