const prohibitedItemsAndActivities = [
    "Alcohol and drugs",
    "Audio recording",
    "Baby carriages",
    "Baby strollers",
    "Bachelor & bachelorette party groups",
    "Party groups",
    "Backpacks",
    "Bags",
    "Bare feet",
    "Bikes",
    "Boots",
    "Bright colors",
    "Cameras",
    "Cellphones",
    "Chewing gum",
    "Climbing",
    "Cooler",
    "Crutches",
    "Diving",
    "Handcarts",
    "Alcoholic drinks in the vehicle",
    "Drinks in the vehicle",
    "Drinks",
    "Drones",
    "Food in the vehicle",
    "Electric wheelchairs",
    "Electronic devices",
    "Explosive substances",
    "Feeding animals",
    "Firework",
    "Fishing",
    "Flashlight",
    "Flash photography",
    "Food",
    "Food and drinks",
    "Food and drinks in the vehicle",
    "Glass objects",
    "Hats",
    "Headphones",
    "High-heeled shoes",
    "Shoes indoors",
    "Insect repellent",
    "Intoxication",
    "Jeans",
    "Jewelry",
    "Jumping",
    "Littering",
    "Luggage or large bags",
    "Making fire",
    "Making noise",
    "Military-style clothing",
    "Mobility scooters",
    "Loose clothing",
    "Non-folding strollers",
    "Non-folding wheelchairs",
    "Waterproof cameras",
    "Nudity",
    "Open-toed shoes",
    "Oversize luggage",
    "Padlocks",
    "Pets",
    "Pets (assistance dogs allowed)",
    "Photography inside",
    "Plastic bags",
    "Plastic bottles",
    "Professional cameras",
    "Red wine",
    "Riding the animals",
    "Ripped clothing",
    "Sandals or flip flops",
    "Scooter",
    "See-through clothing",
    "Selfie sticks",
    "Shoes",
    "Shorts",
    "Short skirts",
    "Skateboards",
    "Skates",
    "Skirts",
    "Sleeveless shirts",
    "Slippers",
    "Smoking",
    "Smoking indoors",
    "Smoking in the vehicle",
    "Snorkeling",
    "Speakers",
    "Sports shoes",
    "Sportswear",
    "Sprays or Aerosols",
    "Strong fragrances",
    "Sunglasses",
    "Sunscreen",
    "Surfboards",
    "Swimming",
    "Swimwear",
    "Tablets/iPads",
    "Tight clothing",
    "Touching the exhibits",
    "Touching marine life",
    "Touching animals",
    "Touching plants",
    "Tripods",
    "Umbrellas",
    "Unaccompanied minors",
    "Visible tattoos",
    "Valuables",
    "Vaping",
    "Video recording",
    "Walking frames",
    "Walking sticks",
    "Weapons or sharp objects",
    "Wearing a costume"
  ]
  

  export default prohibitedItemsAndActivities