const  requiredAndRecommendedItems = [
    "Beachwear",
    "Binoculars",
    "Biodegradable sunscreen",
    "Biodegradable insect repellent",
    "Boating licence",
    "Camera",
    "Cash",
    "Change of clothes",
    "Charged Smartphone",
    "Child safety seat",
    "Climbing gear",
    "Closed-toe shoes",
    "Clothes that can get dirty",
    "Collared shirt",
    "Comfortable clothes",
    "Comfortable shoes",
    "Cooking equipment",
    "Credit card",
    "Cycling clothing",
    "Daypack",
    "Deposit",
    "Disability card",
    "Dive log",
    "Diving certification",
    "Downloaded app",
    "Drinks",
    "Driver's license",
    "Face mask or protective covering",
    "FFP2 mask",
    "First aid kit",
    "Fishing license",
    "Flashlight",
    "Flip-flops",
    "Food",
    "Food and drinks",
    "Game box",
    "Garbage bag",
    "Gloves",
    "Goggles",
    "Trekking gear",
    "GPS/map",
    "Hair tie",
    "Hand sanitizer or tissues",
    "Hat",
    "Head covering or kippah",
    "Headphones",
    "Headscarf",
    "Helmet",
    "Hiking pants",
    "Hiking shoes",
    "Ingredients",
    "Insect repellent",
    "International driver's license",
    "Internet access",
    "Jacket",
    "Breathable clothing",
    "Long pants",
    "Long-sleeved shirt",
    "Medical mask",
    "Medical statement",
    "Motion sickness prevention",
    "Outdoor clothing",
    "Pacemaker card",
    "Packed lunch",
    "Passport",
    "Passport, copy accepted",
    "Passport or ID card",
    "Passport or ID card for children",
    "Passport or ID card, copy accepted",
    "Passport-sized photo",
    "Pen",
    "Personal medication",
    "Pillow",
    "Power bank",
    "Public transport ticket",
    "Quick-dry clothing",
    "Rain gear",
    "Reusable water bottle",
    "Sandals",
    "Sarong",
    "Scarf",
    "Shorts",
    "Signed waiver",
    "Sleeping bag",
    "Snacks",
    "Snorkeling gear",
    "Snow clothing",
    "Socks",
    "Sports shoes",
    "Sportswear",
    "Storage device",
    "Student card",
    "Sunglasses",
    "Sun hat",
    "Sunscreen",
    "Swimming cap",
    "Swimwear",
    "Tent",
    "Thermal clothing",
    "Tie",
    "Toiletries",
    "Towel",
    "Travel insurance",
    "Tripod",
    "T-shirt",
    "Umbrella",
    "ID card, copy accepted",
    "Visa, if required",
    "Warm clothing",
    "Warm shoes",
    "Water",
    "Waterproof bag",
    "Waterproof camera",
    "Waterproof shoes",
    "Water shoes",
    "Weather-appropriate clothing",
    "Wetsuit",
    "Windbreaker",
    "Winter sports gear",
    "Your own vehicle"
  ]
  


export default requiredAndRecommendedItems