export const dynamic = "force-dynamic";
export const dynamic = "force-dynamic";
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: any
}) {
	console.log('params', params)

	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
