const BookingStates = {
	INITIAL: 'INITIAL',
	SELECTING_DATES: 'SELECTING_DATES',
	CONFIRMING_DETAILS: 'CONFIRMING_DETAILS',
	PROCESSING_PAYMENT: 'PROCESSING_PAYMENT',
	CONFIRMED: 'CONFIRMED',
	COMPLETED: 'COMPLETED',
	AWAITING_CUSTOMER_REVIEW: 'AWAITING_CUSTOMER_REVIEW',
	CUSTOMER_REVIEWED: 'CUSTOMER_REVIEWED',
	EXPIRED: 'EXPIRED',
	CANCELLED: 'CANCELLED',
}
export default BookingStates
